//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Design
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class boxingEntities : DbContext
    {
        public boxingEntities()
            : base("name=boxingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BoxDetailTable> BoxDetailTable { get; set; }
        public virtual DbSet<BoxMasterTable> BoxMasterTable { get; set; }
        public virtual DbSet<ProductTable> ProductTable { get; set; }
    }
}
